name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-astro
      cancel-in-progress: true

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Cache de dependências
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 5. Construir o projeto
      - name: Build project
        run: npm run build

      # 6. Listar arquivos para depuração
      - name: List build output
        run: ls -R ./dist

      # 7. Garantir o arquivo CNAME
      - name: Ensure CNAME file
        run: echo "www.lytspot.com.br" > ./dist/CNAME

      # 8. Deploy para a branch gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false  # Substitui todos os arquivos antigos na branch gh-pages
